### ISSUE TITLE
Bug: can't open file "fs/sdcardfs/s/Kconfig

### ISSUE THREAD

**Issue by Besix2** [grm34/ZenMaxBuilder#228]
**Describe the bug**
When compiling it return error:
`make: Entering directory '/home/besi/Downloads/SM-A750FN_EUR_PP_Opensource/Kernel'

make[1]: Entering directory '/home/besi/ZenMaxBuilder/out/a7y18lte'

  HOSTCC  scripts/basic/fixdep

  HOSTCC  scripts/basic/bin2c

  GEN     ./Makefile

  HOSTCC  scripts/kconfig/conf.o

  HOSTCC  scripts/kconfig/zconf.tab.o

  HOSTLD  scripts/kconfig/conf

fs/sdcardfs/Kconfig:5: can't open file "fs/sdcardfs/s/Kconfig"

make[2]: *** [/home/besi/Downloads/SM-A750FN_EUR_PP_Opensource/Kernel/scripts/kconfig/Makefile:110: exynos7885-
a7y18lte_defconfig] Error 1

make[1]: *** [/home/besi/Downloads/SM-A750FN_EUR_PP_Opensource/Kernel/Makefile:563: exynos7885-a7y18lte_defconfig] Error 2

make[1]: Leaving directory '/home/besi/ZenMaxBuilder/out/a7y18lte'

make: *** [Makefile:150: sub-make] Error 2

make: Leaving directory '/home/besi/Downloads/SM-A750FN_EUR_PP_Opensource/Kernel'
`

**Expected behavior**
It should compile without errors.
**Logfile**
If applicable, add the logfile from logs/DEVICE-CODENAME:

- Logile is empty

**Screenshots**
![Screenshot from 2022-05-01 11-24-33](https://user-images.githubusercontent.com/92743858/166143544-d2e37a04-2ede-4ed4-9c1f-48ccd2369b3c.png)

**Desktop (please complete the following information):**

- OS: Ubuntu
- Terminal used: standart Terminal
- Bash version: / 

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy A7 2018 FN (SM-A750FN)
- OS: android 10
- Termux: no tremux (ubuntu(newest))
- Bash version: /
**Additional context**

**Comment by grm34** [comment]
It's kernel source related (Makefile needs some changes).

Try to make config without ZenMaxBuilder and see if same error:

    make -C /home/besi/Downloads/SM-A750FN_EUR_PP_Opensource/Kernel O=/home/besi/ZenMaxBuilder/out/a7y18lte ARCH=arm64 exynos7885-a7y18lte_defconfig

Or directly from your kernel path:

    cd /home/besi/Downloads/SM-A750FN_EUR_PP_Opensource/Kernel
    make O=out ARCH=arm64 exynos7885-a7y18lte_defconfig

Edit: https://github.com/grm34/ZenMaxBuilder#warning

**Comment by grm34** [comment]
Just change `PLATFORM_VERSION` and `ANDROID_MAJOR_VERSION` in ZMB settings :

    vi etc/user.cfg

Your kernel source was designed for Android 10
