### ISSUE TITLE
Bug: Error: Os not found, some dependencies may  be required (hole thing doesnt work)

### ISSUE THREAD

**Issue by Besix2** [grm34/ZenMaxBuilder#500]
**Describe the bug**
When starting ZenMaxBuilder it begins at asking anykernel clone and if said yes it fails.

**Expected behavior**
Should start normaly

**Logfile**
no logs
**Screenshots**
![image](https://user-images.githubusercontent.com/92743858/170872298-3098d4bd-4cb8-4c68-8eed-aa2070e4f476.png)

**Desktop (please complete the following information):**

- OS: ArchLinux
- Terminal used: included terminal
- Bash version:  5.1.16

**Smartphone (please complete the following information):**

- Device: Sm-A750FN (a7y18lte)
- OS: android 10

**Comment by grm34** [comment]
Why running with sudo?

The package manager is detected with `which` built-in, so what's the output of `which pacman` ?

Anyway, you can also manualy install dependencies and set `AUTO_DEPENDENCIES` to `False` in `user.cfg`

**Comment by Besix2** [comment]
I will try it. I run sudo because it said that permission is denied.

**Comment by grm34** [comment]
I guess `expect` is missing
