### ISSUE TITLE
Help: Error: CROSS_COMPILE not found on makefile!!

### ISSUE THREAD

**Issue by invincible-man** [grm34/ZenMaxBuilder#614]
Clang AOSP were cpoied inside toolchain dir but i still getting this error, also tried diffrent kernel source but the error keep showing.?

**Comment by grm34** [comment]
Hi.

- Which OS are you on?
- Shell (sh, zsh, fish...)?

Also nice to know `bash` and `sed` and `grep` versions and at least a link to a kernel source code used.

**Comment by invincible-man** [comment]
Hi, thx for a quick reply .

* Which OS are you on? Tried several OS ( Ubuntu 21 LTS, Fedora, Kali,Manjaro) had same error.

*  Shell (sh, zsh, fish...) Shell was actually sh and zsh as i tried fish as well .. Other OS they were set on default shell .
I might experiencing some difficulties on how to navigate TC in a proper dir, or makefile thet i had inside kernel dir doesn't recognize TC dir that i recently added .

I Would be very thankful for more assit from ur end..!

**Comment by grm34** [comment]
Weird, all those OS natively or from chroot, proot, wm, wsl stuff?

A screenshot of the error will be helpful.

Seems not TC related but the `sed` command to get `Makefile` values.

edit: #615 I have simplified the obtaining of values, `grep` is more appropriate here.

**Comment by invincible-man** [comment]
![Screenshot from 2022-06-17 18-03-11](https://user-images.githubusercontent.com/69092834/174407229-9010d314-a65f-4514-bc63-645effa51855.jpeg)

**Comment by grm34** [comment]
Thanks, that's what I was thinking. Check my edit above :

    edit: #615 I have simplified the obtaining of values, grep is more appropriate here

Update and let me know.

edit: #618 #619 should also help.

**Comment by grm34** [comment]
@invincible-man I got it, `CROSS_COMPILE` is not set in your kernel [Makefile](https://raw.githubusercontent.com/flar2/OnePlus8/ElementalX-2.00/Makefile) (I guess that's configured to be defined as `make` command-line argument).

This kind of configuration was not handled by `zmb`. I'm going to fix that soon.

Thanks for reporting.

edit: ✅ fixed by #620

**Comment by invincible-man** [comment]
Awesome, thank you so much, this will much handled by everyone who wish to
compile his own kernel tho, pls keep me notified when it's got fixed so I
can test it out and feedback for any undefined matter..!

**Comment by grm34** [comment]
@invincible-man ✅ fixed by #620 and #622
