### ISSUE TITLE
Help/Bug: Invalid cross-device link

### ISSUE THREAD

**Issue by Lyahi** [grm34/ZenMaxBuilder#725]
- OS: (ArchLinux)
- Terminal used: (xfce termianl)
- Bash version: (5.1.16)
```
/         	ext4
/home     	xfs
```
Hi @grm34,
The installation of the script ends with the following message/error.
> ln: failed to create hard link '/usr/bin/zmb' => '/home/sunfizz/ZenMaxBuilder/src/zmb.sh': Invalid cross-device link

**Comment by grm34** [comment]
Hello.

Hardlink over different mountpoints issue. Should be fixed #726 

Thanks for reporting.
