### ISSUE TITLE
Help: included toolchains not compatible on Termux

### ISSUE THREAD

**Issue by Saikatsaha1996** [grm34/ZenMaxBuilder#732]
in your screen shot you useing android device
But i am getting error how can I solve?

![Screenshot_2022-07-31-18-54-43-332_tech ula](https://user-images.githubusercontent.com/72664192/182028526-798e5c85-430d-45ee-beb9-8b91af3de010.jpg)

**Comment by grm34** [comment]
Hello.

Included prebuilt toolchains are for x86_64 hosts, see https://github.com/grm34/ZenMaxBuilder#toolchains

You can disable `HOST_LINKER` in `etc/user.cfg` to bypass the warning but the build will fail.

Kernel compilation on Termux is pain, you can try to build your own toolchains or use stuff like proot.

**Comment by Saikatsaha1996** [comment]
> Hello.
> 
> Included prebuilt toolchains are for x86_64 hosts, see https://github.com/grm34/ZenMaxBuilder#toolchains
> 
> You can disable `HOST_LINKER` in `etc/user.cfg` to bypass the warning but the build will fail.
> 
> Kernel compilation on Termux is pain, you can try to build your own toolchains or use stuff like proot.

I am not useing termux.. i am useing userland like proot

**Comment by Saikatsaha1996** [comment]
> Hello.
> 
> Included prebuilt toolchains are for x86_64 hosts, see https://github.com/grm34/ZenMaxBuilder#toolchains
> 
> You can disable `HOST_LINKER` in `etc/user.cfg` to bypass the warning but the build will fail.
> 
> Kernel compilation on Termux is pain, you can try to build your own toolchains or use stuff like proot.

And i really don't know how to build toolchain.. 

Can it not possible build in userland or termux proot-distro?

**Comment by grm34** [comment]
Userland on Termux, but I would like to say on Android to be more precise.

See https://github.com/grm34/ZenMaxBuilder#common-warnings-and-errors

x86_64 prebuilts needs x86_64 host, simple of that.

**Comment by Saikatsaha1996** [comment]
> Userland on Termux, but I would like to say on Android to be more precise.
> 
> See https://github.com/grm34/ZenMaxBuilder#common-warnings-and-errors
> 
> x86_64 prebuilts needs x86_64 host, simple of that.

Now see useing x86_64 host..

![IMG_20220731_194706](https://user-images.githubusercontent.com/72664192/182030648-49654902-4180-455f-82b4-b81299f4eee1.jpg)

**Comment by grm34** [comment]
I'm not going to do kernel building support here...
See https://github.com/grm34/ZenMaxBuilder#more-information

I help this time: see the error "CROSS_COMPILE_ARM32 not defined" 👉 check/edit your makefile

**Comment by Saikatsaha1996** [comment]
I solved my problem with this way.. `(host-clang)`
`Userland-android`
![IMG_20220801_023035](https://user-images.githubusercontent.com/72664192/182045169-a90a0ece-d7c8-4fdc-a5c2-fefca869e5aa.jpg)

**Comment by Saikatsaha1996** [comment]
@grm34  zmb segmentation fault and freeze, 

![Screenshot_2022-09-02-00-23-00-524_tech ula](https://user-images.githubusercontent.com/72664192/187991636-4bea5d2c-aa29-4e28-aa47-45b474a5d2f0.jpg)

**Comment by grm34** [comment]
> @grm34 zmb segmentation fault and freeze,
> 
> ![Screenshot_2022-09-02-00-23-00-524_tech ula](https://user-images.githubusercontent.com/72664192/187991636-4bea5d2c-aa29-4e28-aa47-45b474a5d2f0.jpg)

A package seems broken or an instance of zmb is not well closed.
Try to purge your cache, upgrade your system and identify broken package then reboot.

Some informations are asked while opening an issue:

    - OS name and version
    - bash version
    - running shell
    - terminal used
    - ...
