### ISSUE TITLE
Question: kernel building support?

### ISSUE THREAD

**Issue by Lyahi** [grm34/ZenMaxBuilder#733]
Hi, Could you please provide an email or telegram contact for yourself. I have a few questions on the topic of building a kernel.

Best.

**Comment by grm34** [comment]
Hello. Sorry but I don't do kernel building support. There was a dedicated TG group but most people came without knowledge of kernel building, figuring I was going to debug everything for them. ZMB is a tool to make building easier and quicker, especially for people who maintain multiple kernels, not a magic one-click thing, basics are required. So the TG group is closed.

**Comment by Lyahi** [comment]
I understand. Thanks for your reply. 🙂
