### ISSUE TITLE
Help: progcomp_alias: invalid shell option name

### ISSUE THREAD

**Issue by Saikatsaha1996** [grm34/ZenMaxBuilder#734]
![IMG_20220814_223329](https://user-images.githubusercontent.com/72664192/184547430-8b86ad7c-5017-4a43-8db7-241110ccd30d.jpg)

**Comment by grm34** [comment]
What's the output of:

`ps -p $$ && bash --version`

**Comment by Saikatsaha1996** [comment]
> What's the output of:
> 
> `ps -p $$ && bash --version`

I will give you update after sometime.. i uninstalled ubuntu 18 and frash installed 22.04 zmb working fine..

**Comment by Saikatsaha1996** [comment]
@grm34 one more thing.. if my_device _defconfig are under arch/arm64/configs/vendor/ 

How can I edit or change my defconfig directory?

**Comment by grm34** [comment]
The defconfig files from vendor folder can now be selected #735 

edit: use `zmb --update` not `git pull` to also update bin

**Comment by Saikatsaha1996** [comment]
> The defconfig files from vendor folder can now be selected #735
> 
> edit: use `zmb --update` not `git pull` to also update bin

Okay thank you 😊

**Comment by grm34** [comment]
Welcome 🙏

**Comment by Saikatsaha1996** [comment]
> Welcome 🙏

I am closing now issue.. i will share my bash version after some time.. thank you for your help

**Comment by grm34** [comment]
Okay, I'm still on smartphone, so let me know. No more need bash version, it was just to understand why `progcomp_alias` was not a valid option.

**Comment by Saikatsaha1996** [comment]
> Okay, I'm still on smartphone, so let me know. No more need bash version, it was just to understand why `progcomp_alias` was not a valid option of your shell.

i was installed old ubuntu in my vm now this issue solved working like charms.. but sometimes toolchain problem found `aarch64-linux-gnu-gcc not fund`..

Now useing `proton clang` getting another error and search in google for this error.. i found one like fully same.. problem for toolchain.. don't know why.. 


![IMG_20220815_030910](https://user-images.githubusercontent.com/72664192/184556679-08e08d0c-c542-4f7c-bf79-f377a7c18336.jpg)

**Comment by Saikatsaha1996** [comment]
> Okay, I'm still on smartphone, so let me know. No more need bash version, it was just to understand why `progcomp_alias` was not a valid option.

Which toolchain are you useing for smartphones? Host or another one? If you don't mind can you share, if you are useing another one?

**Comment by grm34** [comment]
For `aarch64-linux-gnu-gcc not found`: seems some dependencies are missing, try `apt install gcc-aarch64-linux-gnu`.

For `proton-clang` error: try to activate LTO in `user.cfg`, but it's kernel related and it's better to use the same compiler at the beginning.

edit: I meant same compiler as your source. If built with gcc use gcc...

**Comment by Saikatsaha1996** [comment]
Okay trying

**Comment by grm34** [comment]
> > Okay, I'm still on smartphone, so let me know. No more need bash version, it was just to understand why `progcomp_alias` was not a valid option.
> 
> Which toolchain are you useing for smartphones? Host or another one? If you don't mind can you share, if you are useing another one?

Try Host compiler on proot, but like I said you must use same.

**Comment by Saikatsaha1996** [comment]
> > > Okay, I'm still on smartphone, so let me know. No more need bash version, it was just to understand why `progcomp_alias` was not a valid option.
> > 
> > 
> > Which toolchain are you useing for smartphones? Host or another one? If you don't mind can you share, if you are useing another one?
> 
> Try Host compiler on proot, but like I said you must use same.

Yes useing.. working...

**Comment by Saikatsaha1996** [comment]
> > > Okay, I'm still on smartphone, so let me know. No more need bash version, it was just to understand why `progcomp_alias` was not a valid option.
> > 
> > 
> > Which toolchain are you useing for smartphones? Host or another one? If you don't mind can you share, if you are useing another one?
> 
> Try Host compiler on proot, but like I said you must use same.

Can I get some help for this ?..

![Screenshot_2022-08-15-10-03-05-549_tech ula](https://user-images.githubusercontent.com/72664192/184579167-04b959dc-542b-4d20-bf6d-ccedd48d0ca4.jpg)

**Comment by grm34** [comment]
> > > > Okay, I'm still on smartphone, so let me know. No more need bash version, it was just to understand why `progcomp_alias` was not a valid option.
> > > 
> > > 
> > > Which toolchain are you useing for smartphones? Host or another one? If you don't mind can you share, if you are useing another one?
> > 
> > 
> > Try Host compiler on proot, but like I said you must use same.
> 
> Yes useing.. working...

Stop using weird env to compile and use real linux...

**Comment by Saikatsaha1996** [comment]
> > Okay, I'm still on smartphone, so let me know. No more need bash version, it was just to understand why `progcomp_alias` was not a valid option of your shell.
> 
> i was installed old ubuntu in my vm now this issue solved working like charms.. but sometimes toolchain problem found `aarch64-linux-gnu-gcc not fund`..
> 
> Now useing `proton clang` getting another error and search in google for this error.. i found one like fully same.. problem for toolchain.. don't know why..
> 
> ![IMG_20220815_030910](https://user-images.githubusercontent.com/72664192/184556679-08e08d0c-c542-4f7c-bf79-f377a7c18336.jpg)

Useing real Linux getting this error.. that's why useing android but after 99% getting this error..

**Comment by grm34** [comment]
> > > Okay, I'm still on smartphone, so let me know. No more need bash version, it was just to understand why `progcomp_alias` was not a valid option of your shell.
> > 
> > 
> > i was installed old ubuntu in my vm now this issue solved working like charms.. but sometimes toolchain problem found `aarch64-linux-gnu-gcc not fund`..
> > Now useing `proton clang` getting another error and search in google for this error.. i found one like fully same.. problem for toolchain.. don't know why..
> > ![IMG_20220815_030910](https://user-images.githubusercontent.com/72664192/184556679-08e08d0c-c542-4f7c-bf79-f377a7c18336.jpg)
> 
> Useing real Linux getting this error.. that's why useing android but after 99% getting this error...

So it's your starting point now. Stay on this and stop trying vms, android, chroot or stuff like that, that will not help.

**Comment by Saikatsaha1996** [comment]
> > > Okay, I'm still on smartphone, so let me know. No more need bash version, it was just to understand why `progcomp_alias` was not a valid option of your shell.
> > 
> > 
> > i was installed old ubuntu in my vm now this issue solved working like charms.. but sometimes toolchain problem found `aarch64-linux-gnu-gcc not fund`..
> > Now useing `proton clang` getting another error and search in google for this error.. i found one like fully same.. problem for toolchain.. don't know why..
> > ![IMG_20220815_030910](https://user-images.githubusercontent.com/72664192/184556679-08e08d0c-c542-4f7c-bf79-f377a7c18336.jpg)
> 
> Useing real Linux getting this error.. that's why useing android but after 99% getting this error..

Actually i found in google it is toolchain (binutlis) problem..

**Comment by grm34** [comment]
First you have to determine the compiler used by the source. For example if source compiled on x86_64 host with aosp clang, use aosp clang on x86_64 (not on vm). It's the only way to get less compilation warnings. And first compile the source untouched with original defconfig. Then when you'll get successful build you'll can start to add stuff. Your quoted message don't help at all: once use of gcc, once clang... Do this and provide full log

**Comment by Saikatsaha1996** [comment]
> First you have to determine the compiler used by the source. For example if source compiled on x86_64 host with aosp clang, use aosp clang on x86_64 (not on vm). It's the only way to get less compilation warnings. And first compile the source untouched with original defconfig. Then when you'll get successful build you'll can start to add stuff. Your quoted message don't help at all: once use of gcc, once clang... Do this and provide full log

Okay i will update
Also i am still now not edited any kernel configuration..
I am also waiting for fast successfully compile

**Comment by grm34** [comment]
Okay. You must also understand that if the source is from 2018 for example, it have been compiled with an old version of clang or gcc so you will undoubtedly have to make changes. That is called kernel building.

**Comment by Saikatsaha1996** [comment]
> Okay. You must also understand that if the source is from 2018 for example, it have been compiled with an old version of clang or gcc so you will undoubtedly have to make changes. That is called kernel building.

Yes my kernel version 4.19.113 mey be 2018 or newer..

**Comment by Saikatsaha1996** [comment]
See this one lineage - gcc 
gcc not found
![IMG_20220815_171629](https://user-images.githubusercontent.com/72664192/184630008-8c2e6465-ed75-4121-bb0e-855f6bafc266.jpg)

Already available in my usr/bin path

![IMG_20220815_171743](https://user-images.githubusercontent.com/72664192/184630018-f40764c4-e673-4e4d-88f7-12e4405fdfd3.jpg)

Already available los toolchain

![IMG_20220815_172041](https://user-images.githubusercontent.com/72664192/184630315-811176be-953d-4c83-b62b-9e25be7ec99e.jpg)

**Comment by Saikatsaha1996** [comment]
> See this one lineage - gcc gcc not found ![IMG_20220815_171629](https://user-images.githubusercontent.com/72664192/184630008-8c2e6465-ed75-4121-bb0e-855f6bafc266.jpg)
> 
> Already available in my usr/bin path
> 
> ![IMG_20220815_171743](https://user-images.githubusercontent.com/72664192/184630018-f40764c4-e673-4e4d-88f7-12e4405fdfd3.jpg)
> 
> Already available los toolchain
> 
> ![IMG_20220815_172041](https://user-images.githubusercontent.com/72664192/184630315-811176be-953d-4c83-b62b-9e25be7ec99e.jpg)

I found problem it is python problem..

But i already installed python 2 and 3 installed.. 
Which python not working
Which python3 && 2 working..

**Comment by grm34** [comment]
(...) What about properly reading error messages and have a look on what is `scripts/gcc-version.sh` why and from where it's called... Now closing issue.
