### ISSUE TITLE
Bug: Incorrect compiler choices

### ISSUE THREAD

**Issue by ZenSirzechs** [grm34/ZenMaxBuilder#740]
When choosing compilers for the first time, it does not download the one you want.

![image](https://user-images.githubusercontent.com/39871161/186393012-2c558c0e-1434-46eb-9089-2fbb3947ba71.png)

**Comment by grm34** [comment]
See README toolchain section, neutron-gcc is neutron-clang vs eva-gcc. If you want only neutron select 4
