### ISSUE TITLE
Help: Error- make -C /mnt/d/doe/root/kernel/dandelion-q-oss clean Line 638: _make_clean From: zmb

### ISSUE THREAD

**Issue by binbard** [grm34/ZenMaxBuilder#761]
![WindowsTerminal_kOvq2ZR0Bf](https://user-images.githubusercontent.com/28684962/215419374-93bbf0be-6197-48c1-b053-bbbfbf2ea5ab.png)

Same result after I try again

**Comment by grm34** [comment]
https://github.com/grm34/ZenMaxBuilder#common-warnings-and-errors

**Comment by binbard** [comment]
@grm34 Thanks. But this error is not listed there

**Comment by grm34** [comment]
@binbard Best answer you'll get posting a screenshot.
