### ISSUE TITLE
Request: arm support [not arm64]

### ISSUE THREAD

**Issue by binbard** [grm34/ZenMaxBuilder#764]
**Is your feature request related to a problem? Please describe.**
Please provide support for arm too.

**Describe the solution you'd like**
I couldn't find a way to compile kernel for arm.

**Describe alternatives you've considered**
After choosing any compiler on zmb, either gcc or clang, all asks for arm64 toolchains.

**Additional context**
I have armv8l architecture on my phone. So kernel not work properly if I flash kernel built for arm64, eg. wifi, bluetooth, hotspot don't work

**Comment by grm34** [comment]
Hi,

ZMB doesn't care of arch or even toolchain. By default It uses precompiled toolchain for x86_64 hosts (most use cases), that means it download (clone) them if no toolchain is found but you can compile the toolchain your fit and use it (see settings.cfg). For target architecture its in there too : `ARCH="arm64"`

edit: it just check that the selected toolchain fits the host

**Comment by binbard** [comment]
Okay Got it. So it is more of a toolchain downloader. Most part you have to do yourself
